[package]
name = "lakonik"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
nom = "8.0.0"
rllm = { version = "1.1.8", features = ["ollama"] }

[dev-dependencies]
rstest = "0.25.0"
