[package]
name = "lakonik"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
nom = "8.0.0"
rig-core = "0.12.0"
tokio = { version = "1.45.0", features = ["full"] }

[dev-dependencies]
rstest = "0.25.0"
